### PR TITLE
add nix-init

### PR DESCRIPTION
**Pull request by figsoda**
nix-init is a command-line tool to generate Nix packages from URLs
https://github.com/nix-community/nix-init

### CODE REVIEW

**Comment by figsoda** [comment]
cc @houstdav000 :)

**Comment by houstdav000** [comment]
Might need to be debased to get the action updated. Then, its probably good

**Review by houstdav000 — APPROVED** [review]
Looks good, though needs a rebase

**Comment by Mic92** [comment]
bors merge

**Pull request merged**
