### PR TITLE
Add ruby-nix

### PR DESCRIPTION
**Pull request by sagittaros**
I am a Nix beginner and this is my first Nix library :)

### CODE REVIEW

**Comment by houstdav000** [comment]
I mean, I guess that description is technically accurate. The _environment_ produced by `nix develop` is indeed reproduceable provided no external paths are used, though in doing so and by then using standard build systems, the created ruby runtime and environment is not.

Normally, the source is itself first added into the immutable nix store so that any code/source changes then propagate to resulting in a differing output NAR (Nix folder/archive) hash. As I understand it, this would allow you to build packages without doing so via impurities (the accessible paths).

Is this a way to use Nix? Yes. Is it the _right_ way to use Nix? IDK about that, or if that's even the purview of this repository to determine or push.

I suppose as long as it's clear in the repository and the list description that there are no guarantees about reproduceability of the build, just some of the build tools/environment, then I'd be okay with it. Perhaps dedicated sections?

I'd like a second opinion though @zimbatm

**Comment by houstdav000** [comment]
Either way, at 3 days old, it's definitely too new for me to know whether or not you'll be actively maintaining it for a decent period of time and so doesn't meet the criteria given by the upstream project (which I thought was in `CONTRIBUTING.md` but apparently is not), though it is interesting, and brings up some valid questions

**Comment by zimbatm** [comment]
On the surface, the project looks pretty nice. It's trying to solve problems for developers instead of packagers which is quite a common tension. I would wait for the project to be exercised more and have at least one or more releases before adding to the list.

@sagittaros something you can do in the meantime is to announce the project on <https://discourse.nixos.org>, so you start gathering some users for the project

**Comment by sagittaros** [comment]
@houstdav000 hey thanks for the feedback! I should really make it clear that its about reproducibility of the environment, which is an issue faced by my colleagues during `bundle install`.  In the recent months we had an explosion of environment issues due to some upgrading to Ventura and some getting the latest m1/m2 laptops. 

@zimbatm thanks! I don't currently have an account there, I think and agree that it's too soon to announce this (and merge this PR). I will reopen this after a month of using this internally in my company :)

**Comment by zimbatm** [comment]
cool, up to you. You can log into discourse with your github account. I think it's alright to tell people that your project exists even if it's still fresh.

**Comment by sagittaros** [comment]
Hi @houstdav000 @zimbatm , I have managed to get this working with my colleagues. It is not perfect, but a decent experience. I have added added some tests to my `bundix` fork, and am now more comfortable in nix repl.

I will try to announce in the nix forum too, some time soon. Would love to have the PR merged.

**Comment by houstdav000** [comment]
It does look like there's been some good work put into it. I'd recommend creating a release first though, as well as optionally adding a GitHub action to automatically update the flake inputs. It may also be worthwhile to try to upstream those changes in that fork of Bundix to the `nix-community/bundix` repository.

**Comment by sagittaros** [comment]
Thanks for the recommendation. For easier review, you can see [the commit here](https://github.com/sagittaros/ruby-nix/commit/a2fb85cb1d449badfde170806c443f0a27f50dff) and the release page [here](https://github.com/sagittaros/ruby-nix/releases).

For bundix, I am afraid I have taken a very different approach and the generated gemset.nix (ruby bundler's equivalent of flake.lock) is not compatible with nix-community's. This is something that I could discuss with @manveru one day maybe?

**Comment by Mic92** [comment]
I don't think many of the former contributor to bundix are still using ruby regularly.
So your project might actually be able to replace bundix in nixpkgs as the primary way of packaging applications.

**Comment by sagittaros** [comment]
Let's give it some time, I think. I would also want to submit this project to nixpkgs one day.

**Comment by sagittaros** [comment]
Some updates!

Most importantly,
1. `bundix` has been [rewritten significantly](https://github.com/nix-community/bundix/compare/master...sagittaros:bundix:main) with improved speed. 
2. Updated the flake template with the overlay from  [nixpkgs-ruby](https://github.com/bobvanderlinden/nixpkgs-ruby).

## The releases:
https://github.com/sagittaros/ruby-nix/releases/tag/v0.1.3
https://github.com/sagittaros/bundix/releases/tag/0.0.2

**Comment by zimbatm** [comment]
Potentially we might want to transfer the ownership of bundix to @sagittaros if @manveru is up for it. Maybe make a bundix 2.x release to clarify that it's not backwards-compatible?

In any case, it's great to see Ruby getting better maintained, thanks!

**Comment by houstdav000** [comment]
Honestly, not a bad idea with @sagittaros contributing so much.

I'll leave a review and try to merge this pr shortly

**Review by houstdav000 — APPROVED** [review]
Entry looks good, and whatever is decided with Bundix, I feel comfortable saying this downstream project is well-maintained.

**Comment by sagittaros** [comment]
Woah, thank you!

**Pull request merged**
