### PR TITLE
add Home Manager Option Search

### PR DESCRIPTION
**Pull request by mipmip**

### CODE REVIEW

**Comment by mipmip** [comment]
I fix some the cachix deploy with an ending dot to fix the Awesome Lint.

**Comment by houstdav000** [comment]
I've reverted the commit for Cachix deploy, so could you possibly either revert yours or `git reset --hard HEAD~1 && git push --force-with-lease`? In the mean time, I'll take a look at your addition.

**Comment by houstdav000** [comment]
Looks like an interesting project. Could use some work for supporting formatting from the docs and maybe an automatic update, but is still definitely usable.

One question I have though is what is the purpose of the imported script on <https://github.com/mipmip/home-manager-option-search/blob/d0e9a9e57e248cbba30f3d3cbf1fdc6b61f66595/index.html#L15>? It doesn't seem to be used by the client-side app, and afaict, doesn't even resolve to an actual address by any of the major DNS providers.

**Comment by mipmip** [comment]
> Looks like an interesting project. Could use some work for supporting formatting from the docs and maybe an automatic update, but is still definitely usable.

Thanks. What do you mean by "supporting formatting from the docs"? You can submit an issue. I'll work on a new release soon. It updates the options every 4 hours with the official home-manager documentation.
 
> One question I have though is what is the purpose of the imported script on https://github.com/mipmip/home-manager-option-search/blob/d0e9a9e57e248cbba30f3d3cbf1fdc6b61f66595/index.html#L15? It doesn't seem to be used by the client-side app, and afaict, doesn't even resolve to an actual address by any of the major DNS providers.

Oh good question. This was an old privacy respecting visitors tracker I used. As you correctly concluded this is not working anymore. I just removed it from the source code.

**Review by houstdav000 — APPROVED** [review]
Project looks good, and statement is well-formatted.

**Comment by houstdav000** [comment]
> > Looks like an interesting project. Could use some work for supporting formatting from the docs and maybe an automatic update, but is still definitely usable.
> 
> Thanks. What do you mean by "supporting formatting from the docs"? You can submit an issue. I'll work on a new release soon. It updates the options every 4 hours with the official home-manager documentation.

Ah. I simply meant in terms of rendering some of the descriptions, where typically code blocks and in-line code will be monospace, sometimes with a background. Otherwise, it's good.

**Comment by mipmip** [comment]
> Ah. I simply meant in terms of rendering some of the descriptions, where typically code blocks and in-line code will be monospace, sometimes with a background.

Will keep this in mind next release.

**Pull request merged**
