### PR TITLE
Fix GitHub action to run against main or master as target branch

### PR DESCRIPTION
**Pull request by houstdav000**
In copying the GitHub action for #1 I just took it as-is, not realizing it only runs on pull requests targeting a "main" branch.

I expanded out the YAML list and added "master" to it, so it should run against the default branch, regardless of its name.

### CODE REVIEW

**Comment by houstdav000** [comment]
Huh, I thought the action had to be merged first before it would run. Today I learned I guess.

**Comment by Mic92** [comment]
Can you rebase, so it triggers a new run?

**Comment by houstdav000** [comment]
Deferring making a pull request on the last issue (`awesome-nix-hpc` being duplicated) until we decide what we want to do in #1

**Comment by houstdav000** [comment]
Alright, all checks pass, so this should be good to merge now

**Pull request merged**
