### PR TITLE
Add nixfmt

### PR DESCRIPTION
**Pull request by manveru**

### CODE REVIEW

**Comment by zimbatm** [comment]
Are you using it?

If the project is production-ready it can go in the "Command Line tools" section.

**Comment by manveru** [comment]
I use it a lot, it might not be perfect and pretty all the time, but for me
consistency is more important. I'll adjust the PR when I get to a computer.

zimbatm <notifications@github.com> schrieb am Fr., 12. Juli 2019, 22:13:

**Comment by fzakaria** [comment]
:+1: It's the nix formatter I have been happy with.

**Comment by zimbatm** [comment]
please update or make a PR so it goes into "Command Line tools"

**Pull request merged**
