### PR TITLE
Add Makes

### LINKED ISSUE #116: Add makes
It'll be awesome to have this here :smiley:

https://github.com/fluidattacks/makes

### PR DESCRIPTION
**Pull request by houstdav000**
Add the Makes CI/CD deployment tool into the "Deployment Tools" section.

Resolves #116.

@jpverde, would you say this description is accurate?

### CODE REVIEW

**Comment by houstdav000** [comment]
Having re-read the repository README.md and looking closer, I realized that I misunderstood what `makes` does. I thought it was a tool for setting up CI/CD systems (perhaps the ambiguity of the word "systems" contributed), but it's more of a framework for writing CI/CD "pipelines" or "workflows", since it's not a tool that provisions CI/CD infrastructure, but is a tool that workers in CI/CD infrastructure would run, or can even be run entirely locally (with the power of Nix and binary caches).

Perhaps a better description might be "A Nix-based CI/CD pipeline framework for building and testing any language, anywhere."? Also moving it from "Deployment Tools" to "Development".

**Comment by jpverde** [comment]
That's a more accurate description of what makes does :smile:

**Comment by houstdav000** [comment]
Alright, take one more look at it, and if it's good, I'll merge.

**Comment by jpverde** [comment]
LGTM :+1:

**Pull request merged**
