### PR TITLE
Overhaul learning section and add a bunch of things

### PR DESCRIPTION
**Pull request by alper**
This is really good and covers a lot. Should probably be most people's introduction to Nix. Not the current number one there.

### CODE REVIEW

**Review by cyntheticfox — CHANGES_REQUESTED** [review]
Move this below the "How to Learn" entry to maintain alphabetical ordering. Otherwise looks good

**Comment by alper** [comment]
That How to Learn Nix series of articles is pretty outdated. Not sure if that makes sense.

Let me make a bigger change with in what direction I'm thinking of here.

**Comment by alper** [comment]
Here:

- Split out Nix language and NixOS as separate learning topics
- Added Zero to Nix which should probably be most people's starting point
- Pulled up nix.dev
- Updated link to Nix Shorts which I've forked and updated (old repo is dead)
- Added the multi-part Rust/Nix series by Amos which is really very good
- Added the nix.dev page on Nix language to the language section

**Review by cyntheticfox — CHANGES_REQUESTED** [review]
Okay -- again, looking to maintain _alphabetical_ ordering.

Breaking out sections doesn't make sense as well when there are only one or two items to even put in the section.

Also, that's 4 new entries. I'm not against reviewing them, but you've made this difficult by putting them all in the same PR, alongside a bunch of formatting and ordering changes, instead of letting each one stand on its own. Nor does it seem appropriate to have multiple copies of the same resource (`nix.dev`) in this list.

Please either present individual suggestions for the items, or consider just reorganization within a single PR, like I did in #158

**Comment by alper** [comment]
> or consider just reorganization within a single PR

I don't understand. Wouldn't this be the reorganization within a single PR?

> Breaking out sections doesn't make sense as well when there are only one or two items to even put in the section.

I think more items would be found for the other sections but I think it makes sense to break these out because they're distinctly different things. A person interested in nixpkgs does not necessarily have to be interested in NixOS.

Also we can maintain alphabetical order but it would mean highly outdated things coming before newer resources.

But OK. Let me know if this can go as a single PR and otherwise I'll break this up in single suggestions.

**Comment by cyntheticfox** [comment]
Yes, this is within a single PR. It isn't _just_ reorganization though, it's a bunch of additions and moves as well.

If these older items are outright incorrect now, we can move them to the `DEPRECATED.md` file to reflect that. Otherwise, I keep them alphabetical in line with `CONTRIBUTING.md`, and formatted like <https://github.com/sindresorhus/awesome/blob/main/awesome.md#make-it-clear-what-the-list-is-about>, as this isn't an ordered list -- it's a _curated_ list of awesome projects. A more comprehensive list, and one that provides a suggested ordering, would be more appropriate for something like [the Wiki](https://nixos.wiki). I do agree NixOS isn't the same as the Nix language and other projects, which is why I advocated for breaking them into their own section in #158, but perhaps NixOS has gotten large enough to warrant its own `awesome` page

**Comment by alper** [comment]
> I do agree NixOS isn't the same as the Nix language and other projects

I'd prefer to never see anything about NixOS but in most places it is the dominant thing that most conversations and questions are about.

**Comment by alper** [comment]
> Yes, this is within a single PR. It isn't _just_ reorganization though, it's a bunch of additions and moves as well.

OK. I'm closing this and I made a bunch of PRs with single additions in each all of which should still be alphabetical.

**Pull request closed without merging**
