### PR TITLE
Add nix community templates

### PR DESCRIPTION
**Pull request by IogaMaster**

### CODE REVIEW

**Review by cyntheticfox — CHANGES_REQUESTED** [review]
So the entry language and placement is fine itself, but is the project ready to go on this list?

The description mentions "many languages", but the project only has 5 languages (maybe _at best_ "a few"), and they look rather... "pre-built" for templates, while not using the `welcomeText` argument or providing much in the way of integration.

Overall, I think this project could use a lot more maturity in the range of supported languages, use of existing toolchains, and documentation of template-dependencies. Hopefully someday Nix has support for argument templating too :face_exhaling:

**Comment by Mic92** [comment]
There are 9 templates now.

**Comment by cyntheticfox** [comment]
So, I like that more languages look supported, but they're kinda inconsistent.

Some of them have `.gitignore`, but not all do, I think the `Zig` build looks bespoke, and sometimes they come with linters (Rust) or tests (Zig), but they usually don't. Biggest thing is probably a lack of welcome text on many, probably which can be standardized with a function like
```nix
mkWelcomeText = { shortDesc, longDesc, path,  buildTools ? [ ], inputs ? [ ] }: {
  inherit path;

  description = shortDesc;

  welcome text = ''
    # ${shortDesc}
    ${longDesc}

    Comes bundled with ${...}
    
    ## More info
    ${...}
  '';
};
```

This is kinda reflected in how few people have starred it. We really need good templates, but these ones are a little too basic to be usable ATM.

**Review by cyntheticfox — APPROVED** [review]
Entry is good, and while the project could use some more language tools and suggestions like the c template, it's still pretty awesome

**Comment by cyntheticfox** [comment]
Probably needs a rebase prior to merge

**Comment by IogaMaster** [comment]
@cyntheticfox Done

The failures do not come from any change I made

**Pull request merged**
