### PR TITLE
Added unattended install

### PR DESCRIPTION
**Pull request by SRGOM**
Link to script that can make unattended installs

### CODE REVIEW

**Comment by zimbatm** [comment]
nice! can you also move nixos-generators in that section?

**Comment by Mic92** [comment]
Does this still work? For me both `nixpart` and `nixpart0` no longer evaluate on NixOS.

**Comment by SRGOM** [comment]
@Mic92 should I feel bad saying that I didn't actually test it- just found it and figured it belongs here...?

**Comment by SRGOM** [comment]
@zimbatm Done.

**Comment by zimbatm** [comment]
@SRGOM no need to feel bad but I think there was a miscommunication. The awesome-nix list is for curated content. Par of being "awesome" is that the project works and is being maintained :)

Let me know, if upstream doesn't work then it might be best to reject this PR

**Comment by SRGOM** [comment]
Haha. Fair point. Let's reject since I went the lustrate way and didn't  manage to confirm that this works.

**Pull request closed without merging**
