### PR TITLE
Add rust-nix-templater to Rust tools section

### PR DESCRIPTION
**Pull request by yusdacra**

### CODE REVIEW

**Comment by houstdav000** [comment]
Looks like a useful tool to me, but I think it could use a bit more documentation, like maybe an examples section in the `README.md` that shows the tool in-use, or even a `.gif` showing it in use.

That and I'll probably try it out later today

**Comment by houstdav000** [comment]
Also, you may want to tag your releases, and possibly write a shell script to generate them for you

**Comment by yusdacra** [comment]
> Looks like a useful tool to me, but I think it could use a bit more documentation, like maybe an examples section in the README.md that shows the tool in-use, or even a .gif showing it in use.

Yeah, I really should record a video and write some examples. I'll do that later today.

> Also, you may want to tag your releases, and possibly write a shell script to generate them for you

I didn't release a version yet, so that's why there is nothing :P

**Comment by yusdacra** [comment]
I have added some [example usage](https://github.com/yusdacra/rust-nix-templater#examples) to readme, how does it look?

**Comment by houstdav000** [comment]
Looks pretty good to me. My biggest hesitancy is since you don't yet have a release version yet. Thanks to semantic versioning though, a 0 major version (i.e. 0.X.X) means that the api/abi isn't yet stable, so you could really tag your current commit as 0.1.0 or something. If someone wants a later version of the package, then they can pull from master.

Other than that, I have a few project recommendations, but I think I'll add them to your project's issues, if that's alright.

**Comment by yusdacra** [comment]
Sure, I can release a 0.1.0. And yeah I would love to hear recommendations!

**Pull request merged**
