### PR TITLE
split section command line tools

### PR DESCRIPTION
**Pull request by milahu**

### CODE REVIEW

**Review by houstdav000 — COMMENTED** [review]
Probably not unreasonable with how many there are. Maybe it's just me, but "Editing" feels too broad as a section name. Maybe "File Manipulation"?

**Comment by milahu** [comment]
"say it in one word"

imho its clear from the context
nix ... command line tools ... editing

**Comment by houstdav000** [comment]
Yes, but you wouldn't call sed just an "editing" tool, and lump it in the same category as say vim or emacs. By that name, all the linters and formatters should belong in there as well

**Comment by houstdav000** [comment]
I think having an editing section would be fine if those kinds of tools like linters and formatters were moved out of "command line tools" then, since they aren't really imperative tools how the others are.

**Comment by milahu** [comment]
> ... lump it in the same category ...

thats why OOP has failed: you cannot force everything into an inheritance hierarchy

in a perfect world, we would use tags, and "compose" lists from filter expressions ...

**Comment by houstdav000** [comment]
Coming back to this, I suppose I could maybe work with an "Editors" section, though trying to use it, I'm not sure how valuable `nix-editor` is as an addition. I suppose if you truly treat Nix files as just attrsets like a programmable form of JSON or something, it's useful, but since it doesn't actually perform any evaluation, I'm not sure of the use case.

Every one I can think of would be better served through a modification to the expression or extraction into pure data like TOML.

Is there something I'm missing?

**Comment by milahu** [comment]
> I'm not sure how valuable `nix-editor` is as an addition

i guess `nix-editor` can edit a subset of nix, which is good enough for some cases
but its the job of the reader to choose his tools

splitting the 14 item section makes it a bit more readable

**Pull request closed without merging**
